import { CVTemplate } from "@/store/cv-editor-store";

/**
 * Professional CV templates inspired by LinkedIn, Canva, and HR best practices.
 * Each template includes full-height sidebar options, color schemes, and typography.
 */
export const CV_TEMPLATES: CVTemplate[] = [
  // ─── Professional / ATS-Friendly ──────────────────────────────────────────
  {
    id: "modern",
    name: "Modern",
    category: "modern",
    description: "Épuré et minimaliste, parfait pour les startups et la tech",
    accentColor: "#F59E0B",
    sidebarColor: "transparent",
    hasSidebar: false,
    sidebarFullHeight: false,
    sidebarWidth: "medium",
    headerStyle: "modern",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-gradient-to-br from-amber-50 to-white",
  },
  {
    id: "classic-dark",
    name: "Classic Sombre",
    category: "professional",
    description: "Sidebar sombre pleine hauteur, classique et élégant",
    accentColor: "#F59E0B",
    sidebarColor: "#1C1917",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "medium",
    headerStyle: "classic",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-stone-900",
  },
  {
    id: "navy-pro",
    name: "Navy Professionnel",
    category: "professional",
    description: "Bleu marine, sérieux et corporate",
    accentColor: "#60A5FA",
    sidebarColor: "#1E293B",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "medium",
    headerStyle: "classic",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-slate-800",
  },
  {
    id: "forest",
    name: "Forest",
    category: "professional",
    description: "Vert forêt, nature et sobriété pour secteurs RSE/Green",
    accentColor: "#34D399",
    sidebarColor: "#064E3B",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "medium",
    headerStyle: "classic",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-emerald-900",
  },
  {
    id: "burgundy",
    name: "Bordeaux",
    category: "executive",
    description: "Rouge bordeaux, raffiné pour profils seniors et cadres",
    accentColor: "#FB7185",
    sidebarColor: "#881337",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "medium",
    headerStyle: "bold",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-rose-900",
  },
  {
    id: "midnight",
    name: "Midnight",
    category: "creative",
    description: "Indigo profond, idéal pour les profils créatifs et design",
    accentColor: "#A78BFA",
    sidebarColor: "#312E81",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "medium",
    headerStyle: "gradient",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-indigo-900",
  },
  {
    id: "charcoal",
    name: "Anthracite",
    category: "modern",
    description: "Gris foncé neutre, polyvalent et moderne",
    accentColor: "#A1A1AA",
    sidebarColor: "#27272A",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "medium",
    headerStyle: "minimal",
    fontHeading: "DM Sans",
    fontBody: "DM Sans",
    preview: "bg-zinc-800",
  },
  // ─── ATS-Optimized (no sidebar) ──────────────────────────────────────────
  {
    id: "ats-clean",
    name: "ATS Clean",
    category: "ats",
    description: "Optimisé ATS, simple colonne, maximum de compatibilité",
    accentColor: "#3B82F6",
    sidebarColor: "transparent",
    hasSidebar: false,
    sidebarFullHeight: false,
    sidebarWidth: "medium",
    headerStyle: "minimal",
    fontHeading: "DM Sans",
    fontBody: "DM Sans",
    preview: "bg-blue-50",
  },
  {
    id: "ats-executive",
    name: "ATS Exécutif",
    category: "ats",
    description: "Format exécutif sans sidebar, structure claire pour ATS",
    accentColor: "#1E293B",
    sidebarColor: "transparent",
    hasSidebar: false,
    sidebarFullHeight: false,
    sidebarWidth: "medium",
    headerStyle: "bold",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-slate-100",
  },
  // ─── Creative ─────────────────────────────────────────────────────────────
  {
    id: "teal-creative",
    name: "Teal Créatif",
    category: "creative",
    description: "Turquoise vibrant, parfait pour les profils marketing/design",
    accentColor: "#2DD4BF",
    sidebarColor: "#134E4A",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "wide",
    headerStyle: "modern",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-teal-900",
  },
  {
    id: "sunset",
    name: "Sunset",
    category: "creative",
    description: "Dégradé chaleureux, original et mémorable",
    accentColor: "#FB923C",
    sidebarColor: "#7C2D12",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "narrow",
    headerStyle: "gradient",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-gradient-to-b from-orange-800 to-rose-900",
  },
  {
    id: "minimal-white",
    name: "Minimal Blanc",
    category: "modern",
    description: "Fond blanc, lignes fines, ultra-minimaliste",
    accentColor: "#18181B",
    sidebarColor: "#F4F4F5",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "narrow",
    headerStyle: "minimal",
    fontHeading: "DM Sans",
    fontBody: "DM Sans",
    preview: "bg-zinc-100",
  },
  // ─── LinkedIn-inspired ────────────────────────────────────────────────────
  {
    id: "linkedin-pro",
    name: "LinkedIn Pro",
    category: "professional",
    description: "Inspiré du format LinkedIn, bleu professionnel",
    accentColor: "#0A66C2",
    sidebarColor: "#0F172A",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "medium",
    headerStyle: "banner",
    fontHeading: "DM Sans",
    fontBody: "DM Sans",
    preview: "bg-blue-900",
  },
  {
    id: "consulting",
    name: "Consulting",
    category: "executive",
    description: "Style cabinet de conseil, sobre et premium",
    accentColor: "#D4AF37",
    sidebarColor: "#0C0A09",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "narrow",
    headerStyle: "split",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-stone-950",
  },
  {
    id: "academic",
    name: "Académique",
    category: "professional",
    description: "Format structuré pour enseignants, chercheurs, doctorants",
    accentColor: "#7C3AED",
    sidebarColor: "transparent",
    hasSidebar: false,
    sidebarFullHeight: false,
    sidebarWidth: "medium",
    headerStyle: "classic",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-violet-50",
  },
  // ─── Custom Visual Templates (with dedicated renderers) ───────────────────
  {
    id: "executive-v1",
    name: "Exécutif V1",
    category: "executive",
    description: "En-tête sombre pleine largeur, sections ALL CAPS avec icônes, sans sidebar — fidèle au modèle classique",
    accentColor: "#1C1917",
    sidebarColor: "transparent",
    hasSidebar: false,
    sidebarFullHeight: false,
    sidebarWidth: "medium",
    headerStyle: "bold",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-stone-900",
  },
  {
    id: "classic-sidebar-v1",
    name: "Sidebar Classique",
    category: "professional",
    description: "Sidebar sombre avec photo, contact et compétences — contenu principal à droite",
    accentColor: "#F59E0B",
    sidebarColor: "#1C1917",
    hasSidebar: true,
    sidebarFullHeight: true,
    sidebarWidth: "medium",
    headerStyle: "classic",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-stone-800",
  },
  {
    id: "timeline-v1",
    name: "Timeline",
    category: "modern",
    description: "Frise chronologique visuelle avec marqueurs de dates, header centré, sections avec icônes rondes",
    accentColor: "#0EA5E9",
    sidebarColor: "transparent",
    hasSidebar: false,
    sidebarFullHeight: false,
    sidebarWidth: "medium",
    headerStyle: "centered",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-sky-50",
  },
  {
    id: "compact-v1",
    name: "Compact 2 colonnes",
    category: "ats",
    description: "Deux colonnes denses — expérience à gauche, compétences/formation à droite, maximum d'information",
    accentColor: "#059669",
    sidebarColor: "transparent",
    hasSidebar: false,
    sidebarFullHeight: false,
    sidebarWidth: "medium",
    headerStyle: "minimal",
    fontHeading: "DM Sans",
    fontBody: "DM Sans",
    preview: "bg-emerald-50",
  },
  {
    id: "creative-v1",
    name: "Créatif Moderne",
    category: "creative",
    description: "Header dégradé, cartes avec ombres, barres de progression pour langues, badges arrondis pour compétences",
    accentColor: "#8B5CF6",
    sidebarColor: "transparent",
    hasSidebar: false,
    sidebarFullHeight: false,
    sidebarWidth: "medium",
    headerStyle: "gradient",
    fontHeading: "Playfair Display",
    fontBody: "DM Sans",
    preview: "bg-gradient-to-br from-violet-500 to-purple-700",
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: "all", label: "Tous" },
  { id: "professional", label: "Professionnel" },
  { id: "modern", label: "Moderne" },
  { id: "creative", label: "Créatif" },
  { id: "executive", label: "Exécutif" },
  { id: "ats", label: "ATS-Optimisé" },
];

export const SIDEBAR_THEMES = [
  { id: "classic-dark", name: "Classic Dark", color: "#1C1917" },
  { id: "navy-pro", name: "Navy Pro", color: "#1E293B" },
  { id: "forest", name: "Forest", color: "#064E3B" },
  { id: "burgundy", name: "Bordeaux", color: "#881337" },
  { id: "midnight", name: "Midnight", color: "#312E81" },
  { id: "charcoal", name: "Anthracite", color: "#27272A" },
  { id: "teal", name: "Teal", color: "#134E4A" },
  { id: "sunset", name: "Sunset", color: "#7C2D12" },
  { id: "light-gray", name: "Gris clair", color: "#F4F4F5" },
  { id: "warm-white", name: "Blanc chaud", color: "#FAFAF9" },
];

export const HEADER_STYLES = [
  { id: "classic", name: "Classique", description: "Nom + titre + contact en ligne" },
  { id: "modern", name: "Moderne", description: "Accent coloré, layout contemporain" },
  { id: "minimal", name: "Minimaliste", description: "Texte simple, très épuré" },
  { id: "bold", name: "Impact", description: "Grande typographie, fort impact visuel" },
  { id: "gradient", name: "Dégradé", description: "Fond dégradé coloré" },
  { id: "split", name: "Bicolore", description: "En-tête divisée en deux blocs" },
  { id: "centered", name: "Centré", description: "Tout centré, symétrique" },
  { id: "banner", name: "Bannière", description: "Style LinkedIn avec bandeau photo" },
];

export function getTemplateById(id: string): CVTemplate {
  return CV_TEMPLATES.find((t) => t.id === id) ?? CV_TEMPLATES[0];
}

export function getSidebarThemeColor(themeId: string): string {
  return SIDEBAR_THEMES.find((t) => t.id === themeId)?.color ?? "#1C1917";
}
